/*
 * SPDX-FileCopyrightText: 2026 PacPort Inc.
 * SPDX-License-Identifier: CC0-1.0
 *
 * M3.2 self-test (Poincaré + Collapse) — runs embedded fixtures, ADR-023.
 * Fixtures generated by hyperfi/tests/gen_m32_fixtures.py.
 */

#pragma once

#include "esp_err.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Runs all M3.2 fixture sets:
 *   1. Poincaré embed (8D), error budget 1e-4 relative.
 *   2. Geodesic distance, error budget 1e-3 absolute.
 *   3. Möbius addition, error budget 1e-4 relative.
 *   4. Collapse Index sequences, error budget 1e-4 relative on CI,
 *      and exact match on FSM state + fall_detected.
 *
 * Returns ESP_OK if all pass, ESP_FAIL otherwise, ESP_ERR_NOT_FOUND if
 * the m32_fixtures.h header has not been generated.
 */
esp_err_t m32_run_self_test(void);

#ifdef __cplusplus
}
#endif
