/*
 * SPDX-FileCopyrightText: 2026 PacPort Inc.
 * SPDX-License-Identifier: CC0-1.0
 *
 * M3.3 self-test (Metrics + Quiet Detector) — runs embedded fixtures, ADR-023.
 * Fixtures generated by hyperfi/tests/gen_m33_fixtures.py.
 */

#pragma once

#include "esp_err.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Runs all M3.3 fixture sets:
 *   1. Per-window metrics (raw_cv, norm_cv, shape_corr, G, n_valid).
 *      Error budget: 1e-3 relative for CVs, 1e-3 abs for shape_corr,
 *                    1e-3 relative for G, exact match for n_valid.
 *   2. Quiet detector debouncer sequence: at each step verify is_quiet
 *      and duration_sec exactly match the reference simulator.
 *
 * Returns ESP_OK if all pass, ESP_FAIL on any mismatch,
 * ESP_ERR_NOT_FOUND if m33_fixtures.h has not been generated.
 */
esp_err_t m33_run_self_test(void);

#ifdef __cplusplus
}
#endif
