/*
 * SPDX-FileCopyrightText: 2026 PacPort Inc.
 * SPDX-License-Identifier: CC0-1.0
 *
 * M3.4 self-test (Fall Detector — Stage I post-filter) — runs embedded
 * fixtures, ADR-023. Fixtures generated by hyperfi/tests/gen_m34_fixtures.py.
 */

#pragma once

#include "esp_err.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Runs all M3.4 fixture sets:
 *   1. Feature extraction over 30-s (ts, C) sequences.
 *      Error budget: 1e-3 absolute on each of [max, mean, std, spike_dur].
 *   2. Cosine matcher in isolation (4-D feature → best ref pattern).
 *      Error budget: 1e-4 absolute on similarity, exact match on idx.
 *   3. End-to-end (ts, C, fall_flag) sequences exercising rising-edge
 *      detection + confidence gating.
 *      Error budget: same as #1 + #2; exact match on triggered + idx.
 *
 * Returns ESP_OK on full pass, ESP_FAIL on any mismatch,
 * ESP_ERR_NOT_FOUND if m34_fixtures.h has not been generated.
 */
esp_err_t m34_run_self_test(void);

#ifdef __cplusplus
}
#endif
