/*
 * SPDX-FileCopyrightText: 2026 PacPort Inc.
 * SPDX-License-Identifier: CC0-1.0
 *
 * proto_codec — see proto_codec.h.
 */

#include "proto_codec.h"

#include <string.h>

#include "esp_log.h"
#include "esp_system.h"  /* esp_get_free_heap_size */
#include "esp_timer.h"

#include "pb.h"
#include "pb_encode.h"
#include "pb_decode.h"

/* Generated by nanopb codegen via CMake; produced from telemetry.proto. */
#include "telemetry.pb.h"

static const char *TAG = "proto_codec";

/* -------------------------------------------------------------------------- */
/* Encoders                                                                    */
/* -------------------------------------------------------------------------- */

static void fill_telemetry(
    const pipeline_telemetry_t *t,
    hyperfi_csi_TelemetryReport *out)
{
    memset(out, 0, sizeof(*out));

    out->timestamp_us         = t->timestamp_us;
    out->collapse_index_max   = t->collapse_index;
    out->collapse_index_mean  = t->collapse_index;   /* M3.5.1 sends raw, refine later */

    /* Poincaré embed — fixed_count:true means the array is always the full 8 floats. */
    for (int i = 0; i < PIPELINE_EMBED_DIM; i++) {
        out->poincare_embed[i] = t->poincare_embed[i];
    }

    out->embedding_norm       = t->embedding_norm;
    out->norm_cv              = t->norm_cv;
    out->raw_cv               = t->raw_cv;
    out->shape_corr           = t->shape_corr;
    out->dynamic_gain         = t->dynamic_gain_G;
    out->quiet_period         = t->quiet_period;
    out->n_valid_subcarriers  = (uint32_t)t->n_valid_subcarriers;

    const char *fsm = (t->fsm_state == PIPELINE_FSM_SPIKE_DETECTED)
                      ? "SPIKE_DETECTED" : "MONITORING";
    /* fsm_state has nanopb max_size:24 in telemetry.options. */
    strncpy(out->fsm_state, fsm, sizeof(out->fsm_state) - 1);
    out->fsm_state[sizeof(out->fsm_state) - 1] = 0;

    out->rssi              = t->rssi_avg;
    out->noise_floor       = t->noise_floor_avg;
    out->csi_fps           = t->csi_fps;
    out->csi_drop_count    = t->csi_drop_count;
    out->n_frames_in_window = (uint32_t)t->n_frames_in_window;

    out->heap_free_bytes = esp_get_free_heap_size();
    out->uptime_ms       = (uint32_t)(esp_timer_get_time() / 1000ULL);
}

int proto_codec_encode_telemetry(
    const pipeline_telemetry_t *t,
    uint8_t                    *buf,
    size_t                      buf_size)
{
    if (!t || !buf) return -1;

    hyperfi_csi_TelemetryReport msg;
    fill_telemetry(t, &msg);

    pb_ostream_t stream = pb_ostream_from_buffer(buf, buf_size);
    if (!pb_encode(&stream, hyperfi_csi_TelemetryReport_fields, &msg)) {
        ESP_LOGE(TAG, "encode telemetry: %s", PB_GET_ERROR(&stream));
        return -1;
    }
    return (int)stream.bytes_written;
}

int proto_codec_encode_alert(
    const pipeline_telemetry_t *t,
    uint8_t                    *buf,
    size_t                      buf_size)
{
    if (!t || !buf) return -1;

    hyperfi_csi_AlertReport msg;
    memset(&msg, 0, sizeof(msg));

    msg.timestamp_us         = t->timestamp_us;
    strncpy(msg.event_type, "fall_detected", sizeof(msg.event_type) - 1);
    msg.collapse_index_peak  = t->collapse_index;
    msg.confidence           = t->fall_confidence;
    msg.best_pattern_idx     = t->fall_best_pattern_idx;
    if (t->fall_best_pattern_name) {
        strncpy(msg.matched_pattern, t->fall_best_pattern_name,
                sizeof(msg.matched_pattern) - 1);
    }

    /* Snapshot is `optional TelemetryReport snapshot = 10` in proto3 syntax —
     * nanopb generates `has_snapshot` boolean for embedded messages. */
    fill_telemetry(t, &msg.snapshot);
    msg.has_snapshot = true;

    pb_ostream_t stream = pb_ostream_from_buffer(buf, buf_size);
    if (!pb_encode(&stream, hyperfi_csi_AlertReport_fields, &msg)) {
        ESP_LOGE(TAG, "encode alert: %s", PB_GET_ERROR(&stream));
        return -1;
    }
    return (int)stream.bytes_written;
}

/* -------------------------------------------------------------------------- */
/* Decoders + accessors (used by m35_proto_test for round-trip)                */
/* -------------------------------------------------------------------------- */

size_t proto_codec_telemetry_struct_size(void)
{
    return sizeof(hyperfi_csi_TelemetryReport);
}

bool proto_codec_decode_telemetry_struct(
    const uint8_t *buf,
    size_t         buf_size,
    void          *out_struct)
{
    if (!buf || !out_struct) return false;
    hyperfi_csi_TelemetryReport *msg = (hyperfi_csi_TelemetryReport *)out_struct;
    memset(msg, 0, sizeof(*msg));
    pb_istream_t stream = pb_istream_from_buffer(buf, buf_size);
    if (!pb_decode(&stream, hyperfi_csi_TelemetryReport_fields, msg)) {
        ESP_LOGE(TAG, "decode telemetry: %s", PB_GET_ERROR(&stream));
        return false;
    }
    return true;
}

#define ACCESS(name, type, field) \
    type proto_codec_get_##name(const void *s) {                              \
        return ((const hyperfi_csi_TelemetryReport *)s)->field;              \
    }

ACCESS(timestamp_us,        uint64_t, timestamp_us)
ACCESS(collapse_index_max,  float,    collapse_index_max)
ACCESS(norm_cv,             float,    norm_cv)
ACCESS(shape_corr,          float,    shape_corr)
ACCESS(dynamic_gain,        float,    dynamic_gain)
ACCESS(quiet_period,        bool,     quiet_period)
ACCESS(rssi,                int32_t,  rssi)
ACCESS(n_frames_in_window,  uint32_t, n_frames_in_window)

#undef ACCESS

size_t proto_codec_get_poincare_embed(const void *s, float out8[8])
{
    const hyperfi_csi_TelemetryReport *m = (const hyperfi_csi_TelemetryReport *)s;
    /* fixed_count:true → the field is always 8 floats. */
    for (int i = 0; i < 8; i++) out8[i] = m->poincare_embed[i];
    return 8;
}

const char *proto_codec_get_fsm_state(const void *s)
{
    return ((const hyperfi_csi_TelemetryReport *)s)->fsm_state;
}
