/*
 * SPDX-FileCopyrightText: 2026 PacPort Inc.
 * SPDX-License-Identifier: CC0-1.0
 *
 * Spatial Shutter self-test — runs embedded fixtures against shutter_process()
 * and logs PASS/FAIL per fixture + overall. ADR-023 M3.1 verify step.
 *
 * Fixtures are generated by hyperfi/tests/gen_shutter_fixtures.py.
 * To enable the test, generate shutter_fixtures.h into main/ then rebuild.
 * If the header is missing, shutter_run_self_test() returns ESP_ERR_NOT_FOUND.
 */

#pragma once

#include "esp_err.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Run the Spatial Shutter self-test.
 *
 * Iterates the embedded fixture set, processes each H_freq input through
 * shutter_process(), and compares the output against the Python-generated
 * expected values. Logs per-fixture PASS/FAIL and max relative error.
 *
 * @return  ESP_OK if all fixtures pass, ESP_FAIL if any fail,
 *          ESP_ERR_NOT_FOUND if fixture header was not generated.
 */
esp_err_t shutter_run_self_test(void);

#ifdef __cplusplus
}
#endif
