/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_HYPERFI_CSI_PROTO_HYPERFI_CSI_TELEMETRY_PB_H_INCLUDED
#define PB_HYPERFI_CSI_PROTO_HYPERFI_CSI_TELEMETRY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _hyperfi_csi_TelemetryReport {
    uint64_t timestamp_us;
    /* Collapse Index (P1 patent — primary motion signal, robust to per-frame
 CSI noise, see ADR-023 errata 2026-04-27). */
    float collapse_index_max;
    float collapse_index_mean;
    /* Poincaré embedding — exactly 8 floats (POINCARE_EMBED_DIM). */
    float poincare_embed[8];
    float embedding_norm;
    /* Per-window metrics (M3.3) — see ADR-023 errata: norm_cv / shape_corr
 are noisy on raw 8-bit ESP32-C5 CSI; telemetry observation only until
 M3.5.x preprocessing lands. */
    float norm_cv;
    float raw_cv;
    float shape_corr;
    float dynamic_gain; /* G — patent 式 8 sum aggregation */
    bool quiet_period;
    uint32_t n_valid_subcarriers;
    /* FSM state — string per ADR-023 §222. */
    char fsm_state[24]; /* "MONITORING" | "SPIKE_DETECTED" */
    /* CSI link health */
    int32_t rssi;
    int32_t noise_floor;
    float csi_fps;
    uint32_t csi_drop_count;
    uint32_t n_frames_in_window;
    /* Device health */
    uint32_t heap_free_bytes;
    uint32_t uptime_ms;
} hyperfi_csi_TelemetryReport;

typedef struct _hyperfi_csi_AlertReport {
    uint64_t timestamp_us;
    char event_type[32]; /* "fall_detected" */
    float collapse_index_peak;
    float confidence;
    char matched_pattern[32];
    int32_t best_pattern_idx;
    /* Latest TelemetryReport snapshot for alert context — embedded per
 ADR-023 §235 so the dashboard can render alerts without a separate
 telemetry lookup. `optional` makes nanopb emit `has_snapshot`. */
    bool has_snapshot;
    hyperfi_csi_TelemetryReport snapshot;
} hyperfi_csi_AlertReport;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define hyperfi_csi_TelemetryReport_init_default {0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, 0, 0, 0, 0, 0, 0, "", 0, 0, 0, 0, 0, 0, 0}
#define hyperfi_csi_AlertReport_init_default     {0, "", 0, 0, "", 0, false, hyperfi_csi_TelemetryReport_init_default}
#define hyperfi_csi_TelemetryReport_init_zero    {0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, 0, 0, 0, 0, 0, 0, "", 0, 0, 0, 0, 0, 0, 0}
#define hyperfi_csi_AlertReport_init_zero        {0, "", 0, 0, "", 0, false, hyperfi_csi_TelemetryReport_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define hyperfi_csi_TelemetryReport_timestamp_us_tag 1
#define hyperfi_csi_TelemetryReport_collapse_index_max_tag 2
#define hyperfi_csi_TelemetryReport_collapse_index_mean_tag 3
#define hyperfi_csi_TelemetryReport_poincare_embed_tag 4
#define hyperfi_csi_TelemetryReport_embedding_norm_tag 5
#define hyperfi_csi_TelemetryReport_norm_cv_tag  6
#define hyperfi_csi_TelemetryReport_raw_cv_tag   7
#define hyperfi_csi_TelemetryReport_shape_corr_tag 8
#define hyperfi_csi_TelemetryReport_dynamic_gain_tag 9
#define hyperfi_csi_TelemetryReport_quiet_period_tag 10
#define hyperfi_csi_TelemetryReport_n_valid_subcarriers_tag 11
#define hyperfi_csi_TelemetryReport_fsm_state_tag 12
#define hyperfi_csi_TelemetryReport_rssi_tag     13
#define hyperfi_csi_TelemetryReport_noise_floor_tag 14
#define hyperfi_csi_TelemetryReport_csi_fps_tag  15
#define hyperfi_csi_TelemetryReport_csi_drop_count_tag 16
#define hyperfi_csi_TelemetryReport_n_frames_in_window_tag 17
#define hyperfi_csi_TelemetryReport_heap_free_bytes_tag 18
#define hyperfi_csi_TelemetryReport_uptime_ms_tag 19
#define hyperfi_csi_AlertReport_timestamp_us_tag 1
#define hyperfi_csi_AlertReport_event_type_tag   2
#define hyperfi_csi_AlertReport_collapse_index_peak_tag 3
#define hyperfi_csi_AlertReport_confidence_tag   4
#define hyperfi_csi_AlertReport_matched_pattern_tag 5
#define hyperfi_csi_AlertReport_best_pattern_idx_tag 6
#define hyperfi_csi_AlertReport_snapshot_tag     10

/* Struct field encoding specification for nanopb */
#define hyperfi_csi_TelemetryReport_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp_us,      1) \
X(a, STATIC,   SINGULAR, FLOAT,    collapse_index_max,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    collapse_index_mean,   3) \
X(a, STATIC,   FIXARRAY, FLOAT,    poincare_embed,    4) \
X(a, STATIC,   SINGULAR, FLOAT,    embedding_norm,    5) \
X(a, STATIC,   SINGULAR, FLOAT,    norm_cv,           6) \
X(a, STATIC,   SINGULAR, FLOAT,    raw_cv,            7) \
X(a, STATIC,   SINGULAR, FLOAT,    shape_corr,        8) \
X(a, STATIC,   SINGULAR, FLOAT,    dynamic_gain,      9) \
X(a, STATIC,   SINGULAR, BOOL,     quiet_period,     10) \
X(a, STATIC,   SINGULAR, UINT32,   n_valid_subcarriers,  11) \
X(a, STATIC,   SINGULAR, STRING,   fsm_state,        12) \
X(a, STATIC,   SINGULAR, INT32,    rssi,             13) \
X(a, STATIC,   SINGULAR, INT32,    noise_floor,      14) \
X(a, STATIC,   SINGULAR, FLOAT,    csi_fps,          15) \
X(a, STATIC,   SINGULAR, UINT32,   csi_drop_count,   16) \
X(a, STATIC,   SINGULAR, UINT32,   n_frames_in_window,  17) \
X(a, STATIC,   SINGULAR, UINT32,   heap_free_bytes,  18) \
X(a, STATIC,   SINGULAR, UINT32,   uptime_ms,        19)
#define hyperfi_csi_TelemetryReport_CALLBACK NULL
#define hyperfi_csi_TelemetryReport_DEFAULT NULL

#define hyperfi_csi_AlertReport_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp_us,      1) \
X(a, STATIC,   SINGULAR, STRING,   event_type,        2) \
X(a, STATIC,   SINGULAR, FLOAT,    collapse_index_peak,   3) \
X(a, STATIC,   SINGULAR, FLOAT,    confidence,        4) \
X(a, STATIC,   SINGULAR, STRING,   matched_pattern,   5) \
X(a, STATIC,   SINGULAR, INT32,    best_pattern_idx,   6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  snapshot,         10)
#define hyperfi_csi_AlertReport_CALLBACK NULL
#define hyperfi_csi_AlertReport_DEFAULT NULL
#define hyperfi_csi_AlertReport_snapshot_MSGTYPE hyperfi_csi_TelemetryReport

extern const pb_msgdesc_t hyperfi_csi_TelemetryReport_msg;
extern const pb_msgdesc_t hyperfi_csi_AlertReport_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define hyperfi_csi_TelemetryReport_fields &hyperfi_csi_TelemetryReport_msg
#define hyperfi_csi_AlertReport_fields &hyperfi_csi_AlertReport_msg

/* Maximum encoded size of messages (where known) */
#define HYPERFI_CSI_PROTO_HYPERFI_CSI_TELEMETRY_PB_H_MAX_SIZE hyperfi_csi_AlertReport_size
#define hyperfi_csi_AlertReport_size             275
#define hyperfi_csi_TelemetryReport_size         174

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
