/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "proto/hyperfi/csi/telemetry.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(hyperfi_csi_TelemetryReport, hyperfi_csi_TelemetryReport, AUTO)


PB_BIND(hyperfi_csi_AlertReport, hyperfi_csi_AlertReport, AUTO)


PB_BIND(hyperfi_csi_EventCSIFrame, hyperfi_csi_EventCSIFrame, AUTO)


PB_BIND(hyperfi_csi_EventWindowSnapshot, hyperfi_csi_EventWindowSnapshot, AUTO)


PB_BIND(hyperfi_csi_EventRawContext, hyperfi_csi_EventRawContext, AUTO)



